apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-actions-demo
  template:
    metadata:
      labels:
        app: github-actions-demo
    spec:
      containers:
      - name: github-actions-demo
        image: YOUR_DOCKER_USERNAME/github-actions-demo:latest
        ports:
        - containerPort: 5000